import { Employee, Gender, Role } from "../components/employees";

export const employeeDummyData: Employee[] = [
  {
    id: 90,
    name: "Kanwar Singh",
    age: "24",
    role: Role.ADMIN,
    dob: "27/03/2000",
    gender: Gender.MALE,
  },
  {
    id: 91,
    name: "KSRajawat",
    age: "24",
    role: Role.ADMIN,
    dob: "27/03/2000",
    gender: Gender.MALE,
  },
  {
    id: 92,
    name: "Roy",
    age: "25",
    role: Role.USER,
    dob: "27/03/2000",
    gender: Gender.MALE,
  },
  {
    id: 93,
    name: "Durgesh",
    age: "24",
    role: Role.GUEST,
    dob: "27/03/2000",
    gender: Gender.MALE,
  },
  {
    id: 94,
    name: "Andrew Tate",
    age: "38",
    role: Role.ADMIN,
    dob: "27/03/1986",
    gender: Gender.MALE,
  },
  {
    id: 95,
    name: "Rajawat",
    age: "40",
    role: Role.ADMIN,
    dob: "27/03/1986",
    gender: Gender.MALE,
  },
  {
    id: 96,
    name: "Ronaldo",
    age: "38",
    role: Role.GUEST,
    dob: "27/03/1986",
    gender: Gender.MALE,
  },
  {
    id: 97,
    name: "Khabib",
    age: "38",
    role: Role.USER,
    dob: "27/03/1986",
    gender: Gender.MALE,
  },
  {
    id: 98,
    name: "Yogi",
    age: "38",
    role: Role.GUEST,
    dob: "27/03/1986",
    gender: Gender.MALE,
  },
  {
    id: 99,
    name: "Laxmi Bai",
    age: "40",
    role: Role.ADMIN,
    dob: "27/03/1986",
    gender: Gender.FEMALE,
  },
  {
    id: 100,
    name: "Tristian Tate",
    age: "34",
    role: Role.USER,
    dob: "27/03/1986",
    gender: Gender.MALE,
  },
  {
    id: 101,
    name: "Maharana Pratap",
    age: "38",
    role: Role.ADMIN,
    dob: "27/03/1986",
    gender: Gender.MALE,
  },
  {
    id: 102,
    name: "Prithvi Raj",
    age: "38",
    role: Role.GUEST,
    dob: "27/03/1986",
    gender: Gender.MALE,
  },
];
